# Generated by Django 4.2.2 on 2023-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.FloatField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("signal", models.IntegerField()),
                ("mark_index", models.TextField(null=True)),
                ("volume", models.FloatField()),
                ("entry_point", models.FloatField()),
                ("exit_point", models.FloatField()),
                ("entry_position", models.FloatField()),
                ("stop_loss", models.FloatField()),
                ("profit", models.FloatField()),
            ],
        ),
    ]
