# Generated by Django 5.0.1 on 2024-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingscript",
            name="ltp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tradingscript",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
