# Generated by Django 5.0.1 on 2024-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_tradingscript_ltp_alter_tradingscript_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingscript",
            name="entry_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tradingscript",
            name="net_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tradingscript",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
