# Generated by Django 5.0.1 on 2024-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tradingscript_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_exposure", models.IntegerField(default=0)),
                ("m2m", models.IntegerField(default=0)),
                ("total_position", models.IntegerField(default=0)),
                ("volatility_risk", models.IntegerField(default=0)),
                ("exit_profit", models.IntegerField(default=0)),
            ],
        ),
    ]
