# Generated by Django 5.0.1 on 2024-01-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_dashboardinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardInfo",
        ),
    ]
